#!/usr/bin/env bash
#
# protections.sh — record how a landing works in every repo a workspace
# manifest names, and gate on drift from the live GitHub API.
#
# For each repo in repos.yaml it reads the facts that decide whether a change
# can be pushed, needs a green check, or needs a human review, and mirrors
# them back into the manifest as generated keys:
#
#   landing                 direct | checks | review | unavailable
#   required_checks         a list of contexts, or none, or unavailable
#   code_owner              a handle, or none, or unavailable
#   protections_fetched_at  UTC, when the three above were measured
#
# visibility is one of the facts fetched, but the manifest already carries a
# hand-written visibility key, so it is checked rather than duplicated. A
# write run corrects it in place and says so; --check reports a difference
# like any other drift.
#
# unavailable is not a synonym for "no protections". A private repo on GitHub
# Free cannot have rulesets at all, and the API answers 403 Upgrade to GitHub
# Pro rather than an empty list, so the two are recorded apart: one is a fact
# about the branch, the other is a plan-upgrade decision. All three generated
# values carry it, because "none" in any of them would read as
# measured-and-empty. Any other API failure is an error, never unavailable.
#
# Sources, per repo: gh api repos/OWNER/REPO for visibility and the default
# branch; gh api repos/OWNER/REPO/rulesets and then each id for its rules;
# and, only when a rule requires a code-owner review, the CODEOWNERS file,
# which is where a handle can be read rather than a boolean. A ruleset counts
# only when it is active and its conditions actually match the default branch
# — a ruleset aimed at a branch name that does not exist protects nothing,
# and has already shipped in this ecosystem once (night-watchman, 2026-09-15).
#
# Usage:
#   protections.sh [--root PATH] [--check] [--dry-run] [--emit-json PATH]
#
#   (no flag)         fetch, then write the generated block into repos.yaml
#   --check           compare recorded against live, write nothing, and exit
#                      non-zero naming every repo that differs
#   --dry-run         print the diff a write would make, and write nothing
#   --emit-json PATH  write the collected facts as JSON
#   --root PATH       the workspace directory. Default: the nearest ancestor
#                      of the current directory holding a repos.yaml.
#
# Exit codes: 0 all good; 1 drift under --check, or a fetch failed; 2 usage.
#
# NOT WIRED UP: the state store. LAB-292 specifies that this script writes
# these facts to LAB-291's state-store CLI as well as to repos.yaml. That CLI
# does not exist yet, so nothing here writes to it. --emit-json produces
# exactly the payload it will take, so wiring it up is a call site rather than
# a rewrite. See the LAB-291 seam at the end of this file.

set -eu

HERE=$(cd "$(dirname "$0")" && pwd)
# shellcheck source=lib/kit.sh
. "$HERE/lib/kit.sh"

die_usage() { echo "protections.sh: $1" >&2; exit 2; }

ROOT=""
MODE="write"
EMIT_JSON=""

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help) show_help ;;
        --root)
            [ $# -ge 2 ] || die_usage "--root needs a PATH"
            ROOT="$2"; shift 2 ;;
        --check)   MODE="check";   shift ;;
        --dry-run) MODE="dry-run"; shift ;;
        --emit-json)
            [ $# -ge 2 ] || die_usage "--emit-json needs a PATH"
            EMIT_JSON="$2"; shift 2 ;;
        *) die_usage "unexpected argument '$1' (try --help)" ;;
    esac
done

if [ -z "$ROOT" ]; then
    ROOT=$(pwd)
    while [ ! -f "$ROOT/repos.yaml" ] && [ "$ROOT" != "/" ]; do
        ROOT=$(dirname "$ROOT")
    done
    [ -f "$ROOT/repos.yaml" ] || die_usage "no repos.yaml here or in any parent; pass --root"
fi
ROOT=$(cd "$ROOT" && pwd)
MANIFEST="$ROOT/repos.yaml"
[ -f "$MANIFEST" ] || die_usage "no manifest at $MANIFEST"

need gh python3
python3 -c 'import yaml' 2>/dev/null || die "PyYAML is required: pip3 install pyyaml"

set +e
python3 - "$MANIFEST" "$MODE" "$EMIT_JSON" <<'PY'
import base64, difflib, fnmatch, json, os, re, subprocess, sys
from datetime import datetime, timezone

import yaml

MANIFEST, MODE, EMIT_JSON = sys.argv[1], sys.argv[2], sys.argv[3]

BEGIN = "# Generated by ai-toolkit/scripts/protections.sh from the live GitHub API."
NOTE = "# Do not hand-edit: protections.sh --check exits non-zero on any drift."
END = "# end generated"
BEGIN_RE = re.compile(r"^\s*# Generated by ai-toolkit/scripts/protections\.sh")
END_RE = re.compile(r"^\s*# end generated\s*$")
UNAVAILABLE = "unavailable"


class Fatal(Exception):
    pass


class Unavailable(Exception):
    pass


def gh_api(path):
    proc = subprocess.run(
        ["gh", "api", path], capture_output=True, text=True)
    if proc.returncode == 0:
        return json.loads(proc.stdout or "null")
    body = {}
    try:
        body = json.loads(proc.stdout or "{}")
    except ValueError:
        pass
    message = (body.get("message") if isinstance(body, dict) else "") or ""
    # The one failure that is a recorded state rather than an error. Matched on
    # the plan message, not on 403 alone, so a scope or permission 403 stays an
    # error instead of being written down as "this repo has no rulesets".
    if str(body.get("status") if isinstance(body, dict) else "") == "403" \
            and "Upgrade to GitHub" in message:
        raise Unavailable(message)
    detail = message or (proc.stderr or "").strip() or "no output"
    raise Fatal("gh api %s failed: %s" % (path, detail))


def slug_of(url):
    match = re.search(r"[:/]([^/:]+)/([^/]+?)(?:\.git)?$", url or "")
    if not match:
        raise Fatal("cannot read OWNER/REPO out of url %r" % url)
    return "%s/%s" % (match.group(1), match.group(2))


def applies_to_default(conditions, default_branch):
    ref = (conditions or {}).get("ref_name") or {}
    full = "refs/heads/%s" % default_branch
    included = False
    for pattern in ref.get("include") or []:
        if pattern in ("~ALL", "~DEFAULT_BRANCH") or fnmatch.fnmatch(full, pattern):
            included = True
            break
    if not included:
        return False
    for pattern in ref.get("exclude") or []:
        if fnmatch.fnmatch(full, pattern):
            return False
    return True


def codeowners_handle(slug, branch):
    for path in (".github/CODEOWNERS", "CODEOWNERS", "docs/CODEOWNERS"):
        try:
            data = gh_api("repos/%s/contents/%s?ref=%s" % (slug, path, branch))
        except (Fatal, Unavailable):
            continue
        if not isinstance(data, dict) or "content" not in data:
            continue
        text = base64.b64decode(data["content"]).decode("utf-8", "replace")
        for line in text.splitlines():
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if parts[0] == "*" and len(parts) > 1:
                return ",".join(parts[1:])
    # A rule requires a code-owner review but no `*` owner resolves. Saying so
    # is the honest record; "none" would read as no code owner required.
    return "required"


def fetch(name, url):
    slug = slug_of(url)
    repo = gh_api("repos/%s" % slug)
    facts = {
        "name": name,
        "slug": slug,
        "visibility": repo.get("visibility"),
        "default_branch": repo.get("default_branch") or "main",
    }
    try:
        listed = gh_api("repos/%s/rulesets" % slug) or []
    except Unavailable:
        facts.update(landing=UNAVAILABLE, required_checks=UNAVAILABLE,
                     code_owner=UNAVAILABLE, rulesets=UNAVAILABLE)
        return facts

    contexts, approvals, code_owner_required = [], 0, False
    for entry in sorted(listed, key=lambda r: r.get("id") or 0):
        detail = gh_api("repos/%s/rulesets/%s" % (slug, entry.get("id")))
        if detail.get("target") != "branch":
            continue
        if detail.get("enforcement") != "active":
            continue
        if not applies_to_default(detail.get("conditions"), facts["default_branch"]):
            continue
        for rule in detail.get("rules") or []:
            params = rule.get("parameters") or {}
            if rule.get("type") == "required_status_checks":
                for check in params.get("required_status_checks") or []:
                    context = check.get("context")
                    if context and context not in contexts:
                        contexts.append(context)
            elif rule.get("type") == "pull_request":
                approvals = max(
                    approvals,
                    int(params.get("required_approving_review_count") or 0))
                code_owner_required = code_owner_required or bool(
                    params.get("require_code_owner_review"))

    if approvals > 0 or code_owner_required:
        landing = "review"
    elif contexts:
        landing = "checks"
    else:
        landing = "direct"
    facts.update(
        landing=landing,
        required_checks=contexts or "none",
        code_owner=(codeowners_handle(slug, facts["default_branch"])
                    if code_owner_required else "none"),
        rulesets=len(listed),
    )
    return facts


def scalar(value):
    return '"%s"' % value if value.startswith("@") else value


def render(facts, stamp, indent):
    out = [indent + BEGIN, indent + NOTE,
           indent + "landing: %s" % facts["landing"]]
    checks = facts["required_checks"]
    if isinstance(checks, list):
        out.append(indent + "required_checks:")
        out.extend(indent + "  - %s" % c for c in checks)
    else:
        out.append(indent + "required_checks: %s" % checks)
    out.append(indent + "code_owner: %s" % scalar(facts["code_owner"]))
    out.append(indent + 'protections_fetched_at: "%s"' % stamp)
    out.append(indent + END)
    return out


def repo_blocks(lines):
    """Yield (name, start, end) for each repo mapping under the repos: key."""
    try:
        top = next(i for i, l in enumerate(lines) if re.match(r"^repos:\s*$", l))
    except StopIteration:
        raise Fatal("no top-level repos: key in the manifest")
    heads = []
    for i in range(top + 1, len(lines)):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        if indent == 0:
            break
        match = re.match(r"^  ([^\s:#][^:]*):\s*$", line)
        if indent == 2 and match:
            heads.append((match.group(1), i))
    ends = []
    for pos, (_, start) in enumerate(heads):
        stop = heads[pos + 1][1] if pos + 1 < len(heads) else None
        if stop is None:
            stop = len(lines)
            for i in range(start + 1, len(lines)):
                line = lines[i]
                if line.strip() and len(line) - len(line.lstrip()) == 0:
                    stop = i
                    break
        ends.append(stop)
    return [(heads[i][0], heads[i][1], ends[i]) for i in range(len(heads))]


def strip_generated(block):
    out, skipping = [], False
    for line in block:
        if BEGIN_RE.match(line):
            skipping = True
            continue
        if skipping:
            if END_RE.match(line):
                skipping = False
            continue
        out.append(line)
    return out


def rewrite(lines, name_to_facts, stamp):
    out = list(lines)
    for name, start, end in reversed(repo_blocks(out)):
        facts = name_to_facts.get(name)
        if facts is None:
            continue
        block = strip_generated(out[start + 1:end])
        body = [i for i, l in enumerate(block)
                if l.strip() and not l.lstrip().startswith("#")]
        if not body:
            raise Fatal("repo %s has no keys to append to" % name)
        last = body[-1]
        indent = " " * (len(block[last]) - len(block[last].lstrip()))
        for i in body:
            if re.match(r"^\s*visibility:", block[i]):
                block[i] = "%svisibility: %s" % (indent, facts["visibility"])
        block[last + 1:last + 1] = render(facts, stamp, indent)
        out[start + 1:end] = block
    return out


def recorded(manifest):
    doc = yaml.safe_load(open(manifest)) or {}
    return {n: (r or {}) for n, r in (doc.get("repos") or {}).items()}


def compare(name, entry, facts):
    differences = []
    if "landing" not in entry:
        return ["%s: no generated block recorded — run protections.sh" % name]
    pairs = [("landing", entry.get("landing"), facts["landing"]),
             ("required_checks", entry.get("required_checks"),
              facts["required_checks"]),
             ("code_owner", entry.get("code_owner"), facts["code_owner"]),
             ("visibility", entry.get("visibility"), facts["visibility"])]
    for key, got, want in pairs:
        if got != want:
            differences.append(
                "%s: %s recorded %r, live %r" % (name, key, got, want))
    return differences


def main():
    text = open(MANIFEST).read()
    lines = text.splitlines()
    entries = recorded(MANIFEST)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    collected, failures = {}, []
    for name, entry in entries.items():
        url = entry.get("url")
        if not url:
            print("skip   %s (no url in the manifest)" % name)
            continue
        try:
            collected[name] = fetch(name, url)
        except Fatal as exc:
            failures.append("%s: %s" % (name, exc))

    for line in failures:
        print("ERROR  %s" % line, file=sys.stderr)

    for name in sorted(collected):
        facts = collected[name]
        checks = facts["required_checks"]
        print("%-20s %-11s %-11s checks=%s code_owner=%s" % (
            name, facts["visibility"], facts["landing"],
            ",".join(checks) if isinstance(checks, list) else checks,
            facts["code_owner"]))

    if EMIT_JSON:
        with open(EMIT_JSON, "w") as handle:
            json.dump({"fetched_at": stamp,
                       "repos": [collected[n] for n in sorted(collected)]},
                      handle, indent=2, sort_keys=True)
            handle.write("\n")
        print("wrote %s" % EMIT_JSON)

    if failures:
        return 1

    if MODE == "check":
        drift = []
        for name in sorted(collected):
            drift.extend(compare(name, entries[name], collected[name]))
        if drift:
            print("protections drift:", file=sys.stderr)
            for line in drift:
                print("  %s" % line, file=sys.stderr)
            return 1
        print("protections --check: %d repos, no drift" % len(collected))
        return 0

    updated = rewrite(lines, collected, stamp)
    rendered = "\n".join(updated) + "\n"
    if rendered == text:
        print("repos.yaml unchanged")
        return 0
    if MODE == "dry-run":
        sys.stdout.writelines(difflib.unified_diff(
            text.splitlines(True), rendered.splitlines(True),
            fromfile=MANIFEST, tofile="%s (would write)" % MANIFEST))
        return 0
    with open(MANIFEST, "w") as handle:
        handle.write(rendered)
    print("wrote %s (%d repos)" % (MANIFEST, len(collected)))
    for name in sorted(collected):
        if entries[name].get("visibility") not in (None, collected[name]["visibility"]):
            print("note   %s: corrected the hand-written visibility key to %s"
                  % (name, collected[name]["visibility"]))
    return 0


try:
    sys.exit(main())
except Fatal as exc:
    print("protections.sh: %s" % exc, file=sys.stderr)
    sys.exit(1)
PY
STATUS=$?
set -e

# LAB-291 seam. The state-store write specified by LAB-292 is not wired up,
# because LAB-291's CLI does not exist yet. --emit-json already produces the
# payload it will consume, so the wiring is a call site here and nothing else
# in this script changes.
if [ "$MODE" != "check" ] && [ "$STATUS" -eq 0 ]; then
    echo "state store: not written — LAB-291's CLI does not exist yet (seam in $0)"
fi

exit "$STATUS"
